### ISSUE TITLE
pip installable

### ISSUE THREAD

**Issue by alvarouc** [dask/dask-searchcv#36]
First, thanks for putting this library up. I find it very useful. 

Could you do this library pip installable so I can add it as a requirement to one of my packages? (https://github.com/alvarouc/polyssifier)

**Comment by mrocklin** [comment]
Hi @alvarouc , yes.  I think that sounds like a good idea.  I think that @jcrist is working hard at changing some of the internals right now, so I suspect that he will want to wait a couple of days.  Are you ok with this delay?

**Comment by alvarouc** [comment]
No problem at all, thanks for the hard work.

**Comment by chkoar** [comment]
@alvarouc in the meanwhile you could change the ```setup.py ```
```python
    install_requires=[
        'mlp',
        'pandas',
        'sklearn',
        'numpy',
        'dask-learn'],
    dependency_links=[
        'git+https://github.com/dask/dask-learn.git@master#egg=dask-learn-0',
    ]
```
And perform the installation like this

```pip install . --process-dependency-links```

**Comment by jcrist** [comment]
The library is now on pypi under `dask-searchcv`. Should be up on conda-forge early this week. Closing.
