### ISSUE TITLE
Works with stock Pipeline now?

### ISSUE THREAD

**Issue by amueller** [dask/dask-searchcv#46]
Hey.
From what I can see this now works with the stock pipeline. Is that correct? That's amazing!
Can you maybe add an example to make that clear? All the blog-posts etc have a dask-sklearn pipeline.

Keep up the great work!

**Comment by jcrist** [comment]
There no longer is a "dask pipeline" - only the `*SearchCV` classes. If you look at the examples in [this blogpost](https://jcrist.github.io/introducing-dask-searchcv.html) all of them just use the scikit-learn `Pipeline` classes. I'll add an example to the docs though.

**Comment by amueller** [comment]
Hmm in the blog post I thing you left both imports in, and it still used
the old module name, I think.

**Comment by jcrist** [comment]
The blogposts from last summer are quite outdated - the library has since been renamed from `dask-learn` to `dask-searchcv`, and the public interface simplified to just `GridSearchCV` and `RandomizedSearchCV`.

**Comment by amueller** [comment]
Ok, I think I was just looking at the old blog posts / getting confused about which blog posts to look at ;)
