### ISSUE TITLE
dask-searchcv incompatible with Dask v0.18

### ISSUE THREAD

**Issue by jtromans** [dask/dask-searchcv#76]
Trying to run dask-searchcv using version 0.2.0 with Dask 0.18.1 and I'm finding that the scheduling back-end 'distributed' is no longer picking up the tasks, and instead they run from the submitting Python kernel instead of the registered worker. The web-ui confirms as much since the tasks fail to show, and instead I see console output in the submitting kernel, as opposed to the dask-worker. 

By downgrading to Dask 0.17.5, this issue is resolved.

**Comment by jtromans** [comment]
Hi @TomAugspurger . I'll try this later this evening. However, I note that you aren't providing a remote scheduler IP address in this example. Perhaps that doesn't matter, but I'll confirm.

**Comment by TomAugspurger** [comment]
In theory, it shouldn't.

If you are connecting to a remote scheduler, I would verify that your
versions of dask, distributed, and dask-searchcv match on all the machines
(see `client.get_versions`).

**Comment by TomAugspurger** [comment]
Closing this in favor of https://github.com/dask/dask-ml/issues/249

**Comment by TomAugspurger** [comment]
This was fixed over in https://github.com/dask/dask-ml/pull/260

It'll be included in the next release of `dask-ml` which is probably sometime in the next week or two.

**Comment by jtromans** [comment]
Thanks
